### ISSUE TITLE
Documentclass Beamer: 'height fill' does not set the height appropriately if frame title exists

### ISSUE THREAD

**Issue by Hotschke** [T-F-S/tcolorbox#7] opened 2015-12-02 15:27 UTC
I like the height control options of tcolorbox. However, `height fill` does not set the height of the tcolorbox to the correct one if using the documentclass beamer and frame titles.

```latex
\documentclass{beamer}
\let\Tiny=\tiny % http://texblog.net/latex-archive/latex-general/beamer-warnings
\usepackage{tcolorbox} 
\tcbuselibrary{breakable}

\begin{document}
\begin{frame}{Frame title}{Subtitle} % too tall tcolorbox
%\begin{frame} % height of tcolorbox looks ok.
  \begin{tcolorbox}[title={My tcolorbox}, height fill]
  content of my tcolorbox
  \end{tcolorbox} 
\end{frame}
\end{document}
```
Is there any chance tcolorbox can take these things into account

I am actually interested in `beamerposter` with a `headline` and `footline`. There seems to exist similar problems deducing the correct remaining vertical space.

**Comment by T-F-S** [comment] 2015-12-04 07:27
A beamer frame is quite different from a normal text page. `height fill` calculates the space until the end of a (normal) page, but this is not a normal page. Therefore, this is not a bug since the feature just cannot be used here.
I am not sure, if there can be an adaption for `beamer`. I put this on my TODO list, but I expect that this could be tricky or impossible. Meanwhile, I close this issue.

**Closed by T-F-S** 2015-12-04 07:27 UTC

**Comment by Hotschke** [comment] 2015-12-04 09:09
I see. Thank you anyhow.
