### ISSUE TITLE
line spacing in plain-theorem with parbox=false and parskip=half- (Komascript)

### ISSUE THREAD

**Issue by tom75de** [T-F-S/tcolorbox#222] opened 2023-03-03 13:49 UTC
Since updated to 6.0.0/6.0.1, the line spacing in the following example is corrupted (line 1 and 2):

```
\documentclass[parskip=half-]{scrreprt}
\usepackage[T1]{fontenc}
\usepackage{lipsum}
\usepackage[theorems,breakable]{tcolorbox}
\tcbset{nonframedstyle/.style={parbox=false,theorem style=plain,coltitle=black,fonttitle=\bfseries\sffamily,separator sign={\ },terminator sign={:\ }}}
\newtcbtheorem{remark}{Bemerkung}{nonframedstyle}{}

\begin{document}
\begin{remark*}{}
  \lipsum[10]
\end{remark*}
\end{document}
```

![1](https://user-images.githubusercontent.com/30664655/222735587-9c1b7027-0210-4a28-a660-ec9652db8bd7.jpg)

Using the option `parskip=full` makes it worse:

![2](https://user-images.githubusercontent.com/30664655/222735778-eeaa7987-b1a5-4278-837b-18043c3874c8.jpg)

I know the option `parbox=false` is experimental in tcolorbox, but since it worked correctly until version 6.0.0, is there a possibility to use both options `parskip=half-` from Komacript and `parbox=false` from tcolorbox together?

**Comment by muzimuzhi** [comment] 2023-03-03 20:54
Caused by interaction between `parbox=false` and `attach title to upper`.

Since v6.0.0, setting `parbox=false` will prepend an extra `\vspace{-\parskip}` to `before title` and similar, see commit [`dabf431`](https://github.com/T-F-S/tcolorbox/commit/dabf431037a381e8eb1402a64e01c4201e68174f#diff-44d905050db2fcf15c6adeec1023018aff520f938884a90e6e5e1128a826ed5bR912-R917).  KomaScript's `parskip=half-` sets a larger `\parskip`, hence makes the difference noticeable.
https://github.com/T-F-S/tcolorbox/blob/a0b2a76a4de0ebbb1665b25e464665662487360e/tex/latex/tcolorbox/tcolorbox.sty#L956-L961

Try this:
```tex
\documentclass[parskip=half-]{scrreprt}
\usepackage[T1]{fontenc}
\usepackage{lipsum}
\usepackage{tcolorbox}

\tcbset{coltitle=black, fonttitle=\bfseries\sffamily}

\def\test{
  \begin{tcolorbox}[attach title to upper={\ }, title={parbox=true}]
    \lipsum[10][1-4]
  \end{tcolorbox}
  
  \begin{tcolorbox}[attach title to upper={\ }, parbox=false, title={parbox=false}]
    \lipsum[10][1-4]
  \end{tcolorbox}
}

\begin{document}
\subsection*{Before}
\test

\makeatletter
\def\tcb@parbox@false@indent{%
  \preto\kvtcb@before@title{\tcb@parbox@before@title}%
  \preto\kvtcb@before@upper{\tcb@parbox@before@upper}%
  \preto\kvtcb@before@lower{\tcb@parbox@before@lower}%
}%

\def\tcb@parbox@before@common{\vspace{-\parskip}\noindent}
\let\tcb@parbox@before@title\tcb@parbox@before@common
\let\tcb@parbox@before@upper\tcb@parbox@before@common
\let\tcb@parbox@before@lower\tcb@parbox@before@common

\tcbset{
  attach title to upper/.append code={
    \let\tcb@parbox@before@title=\@empty
  },
  attach title/.append code={%
    \let\tcb@parbox@before@title=\tcb@parbox@before@common
  },
  % re-init
  attach title
}
\makeatother

\subsection*{After}
\test
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/222826365-16841a47-f799-40e0-902a-0ea5a3935907.png)

**Comment by tom75de** [comment] 2023-03-04 07:30
Thanks for your explanation and solution!

**Comment by T-F-S** [comment] 2023-03-07 17:55
> I know the option `parbox=false` is experimental in tcolorbox, but since it worked correctly until version 6.0.0, is there a possibility to use both options `parskip=half-` from Komacript and `parbox=false` from tcolorbox together?

I still consider `parbox=false` to be experimental, because this option is quite fragile and often has unwanted side effects with other options or packages.

Nevertheless, I figure the problem you detected as a bug. As @muzimuzhi explained and treated in his patch, the attached title imports its own `parbox` correction (a negative `\parskip`) which accumulates to the already present negative `\parskip` of the upper part.

Unfortunately, using `parskip=false` several times would also accumulates further negative `\parskip` values...

I uploaded a fix https://github.com/T-F-S/tcolorbox/commit/fd391e516ddfc93bc44d5ee4c1e394b9938a6974#diff-44d905050db2fcf15c6adeec1023018aff520f938884a90e6e5e1128a826ed5b which will be part of the next release, if nothing new comes up.

**Comment by T-F-S** [comment] 2023-03-17 11:40
Fixed with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2

**Closed** 2023-03-22 11:28 UTC
Labels: bug
