### ISSUE TITLE
Error when using tcolorbox with minted with already set outputdir

### ISSUE THREAD

**Issue by KriPet** [T-F-S/tcolorbox#12] opened 2016-10-13 11:55 UTC
This seems to be related to issue #9.

Trying to use a `\newtcbinputlisting` when you have already imported minted with a set outputdir results in error.

Here's a minimal example:

```
%!TEX output_directory = aux_dir
\documentclass{article}
\usepackage{fullpage}
\usepackage[outputdir=aux_dir]{minted}
\usepackage[minted, most]{tcolorbox}

\newtcbinputlisting[list inside=mypyg]{\inputPython}[1]{%
  listing engine=minted,
  minted language=python,
  listing file={#1},
  minted options={texcl=true},
  listing only,
}

\begin{document}
\inputPython{included.py}
\mintinline{python}|print("Inline!")|
\end{document}
```

This works fine when you remove the `\usepackage[outputdir=aux_dir]{minted}` line, but then the mintinline fails. Are there any ways of using both?

**Comment by T-F-S** [comment] 2016-10-14 13:37
`\mintinline` should work fine for both cases (and does). Especially, `tcolorbox` does not change any settings for `\mintinline`.

With `\tcbinputlisting`, there is an issue or at least an unexpected behaviour which is connected to https://github.com/T-F-S/tcolorbox/issues/9. To solve the problems of https://github.com/T-F-S/tcolorbox/issues/9, the output directory had to be added to the input path for temporarily created files. Unluckily. this also is true for loading files for minted with `\tcbinputlisting`.

So, the current behaviour needs all minted input files to be found following the `outputdir`. In your case, this is `aux_dir`. If you save your `included.py` file into `aux_dir`, compilation should be fine.

Of course, it should be possible to put source files into the source directory. Unfortunately, there is no way to tell, if an input is intended to be for a *source file* or an *auxiliary file*.

To avoid selecting a directory manualy, I propose the following patch:

```
%!TEX output_directory = aux_dir
\PassOptionsToPackage{outputdir=aux_dir}{minted}
\documentclass{article}
\usepackage{fullpage}
\usepackage[minted, most]{tcolorbox}

\makeatletter
\def\tcb@minted@input@listing#1#2#3#4{%
  \edef\temp@a{#4}%
  \ifx\temp@a\@empty%
  \else%
    \toks@=\expandafter{#4}%
    \edef\tcb@temp{\noexpand\usemintedstyle{\the\toks@}}%
    \tcb@temp%
  \fi%
  \toks@=\expandafter{#1}%
  \edef\tcb@temp{\noexpand\inputminted[\the\toks@]}%
  \IfFileExists{\minted@outputdir#3}%
    {\tcb@temp{#2}{\minted@outputdir#3}}%
    {\tcb@temp{#2}{#3}}%
}
\makeatother

\newtcbinputlisting[list inside=mypyg]{\inputPython}[1]{%
  listing engine=minted,
  minted language=python,
  listing file={#1},
  minted options={texcl=true},
  listing only,
}

\begin{document}
\inputPython{included.py}
\mintinline{python}|print("Inline!")|
\end{document}
```

If the included file exists inside the output directory, it is loaded from there. If not, it is loaded (or tried) from the source directory. If there is a file with the same name inside the output AND the source directory AND the source should be loaded, this will not work. Otherwise, I hope it helps.

If nothing new comes up, I will integrate this patch into the next version of `tcolorbox`.

**Comment by KriPet** [comment] 2016-10-14 19:19
Thank you for a quick reply. The patch works perfectly, although as someone new to LaTeX, I can't even begin to understand how it works.

Thanks for a great package.

**Comment by KriPet** [comment] 2016-10-14 23:01
Guess what? Something new came up.

Your patch fixes `\newtcbinputlisting`, but `\newtcblisting` is still broken.

Here's a minimal example, with all three types of listings, as well as your previous patch. This works fine if you remove the output directory code on lines 1 and 3, but gives a "Missing number, treated as zero." error on the custom tcblisting.

```
%!TEX output_directory = aux_dir
\documentclass{article}
\usepackage[outputdir=aux_dir]{minted}
\usepackage[minted, most]{tcolorbox}


\makeatletter
\def\tcb@minted@input@listing#1#2#3#4{%
  \edef\temp@a{#4}%
  \ifx\temp@a\@empty%
  \else%
    \toks@=\expandafter{#4}%
    \edef\tcb@temp{\noexpand\usemintedstyle{\the\toks@}}%
    \tcb@temp%
  \fi%
  \toks@=\expandafter{#1}%
  \edef\tcb@temp{\noexpand\inputminted[\the\toks@]}%
  \IfFileExists{\minted@outputdir#3}%
    {\tcb@temp{#2}{\minted@outputdir#3}}%
    {\tcb@temp{#2}{#3}}%
}
\makeatother


\newtcbinputlisting{\inputPython}[1]{%
  listing engine=minted,
  minted language=python,
  listing file={#1},
  listing only,
}

\newtcblisting{pythonBox}[1]{%
title=#1}

\begin{document}
\inputPython{included.py}{}

\mintinline{python}|print("Inline!")|

\begin{pythonBox}{Box Title}
print("This is a box")
\end{pythonBox}
\end{document}
```

**Comment by T-F-S** [comment] 2016-10-17 13:19
Sorry, but I cannot reproduce this error. Your example code works for `outputdir=aux_dir` and also for compilation without `outputdir` on my system.

I compiled the code above with `pdflatex -shell-escape -output-directory=aux_dir example.tex` on my system.

**Comment by KriPet** [comment] 2016-10-20 07:35
Hmmm... I still can't get it to compile on my system. The file `example.listing` is created in the aux_dir folder, but it only works if I move that file into the project root folder.

Here's an even more minimal example that doesn't work with `pdflatex -shell-escape -output-directory=aux_dir example.tex`:

```
\documentclass{article}
\usepackage[minted, most]{tcolorbox}

\newtcblisting{pythonBox}{}

\begin{document}
\begin{pythonBox}
print("This is a box")
\end{pythonBox}
\end{document}
```

It also doesn't work if I include your fix.
It also doesn't matter if I include `\usepackage[outputdir=aux_dir]{minted}` or not.

So, at least on my system, it seems the problem is that the search path for `pythonBox` doesn't include `aux_dir`.

Maybe you compiled once without `-output-directory`, and thus had a stray `example.listing` already in your root directory?

**Comment by T-F-S** [comment] 2016-10-20 12:56
The example above does'nt work for `pdflatex -shell-escape -output-directory=aux_dir example.tex`, but that is OK, because `minted` needs the output directory to be told.

If the `outputdir` is added (as shown below), `pdflatex -shell-escape -output-directory=aux_dir example.tex` works on my system. `example.listing` is found inside the `aux_dir`.

``` latex
\documentclass{article}
\usepackage[outputdir=aux_dir]{minted}
\usepackage[minted, most]{tcolorbox}

\newtcblisting{pythonBox}{}

\begin{document}
\begin{pythonBox}
print("This is a box")
\end{pythonBox}
\end{document}
```

I used a freshly installed MiKTeX

My log file contains the following lines:

```
Package: minted 2016/07/20 v2.4 Yet another Pygments shim for LaTeX
Package: tcolorbox 2016/07/14 version 3.94 text color boxes

```

**Comment by KriPet** [comment] 2016-10-24 08:55
Running that exact command on that exact file, I get an error. My logfile reads

```
[snip]
(/usr/local/texlive/2016/texmf-dist/tex/latex/listings/lstmisc.sty
File: lstmisc.sty 2015/06/04 1.6 (Carsten Heinz)
)
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/latin1.def
File: latin1.def 2015/03/17 v1.2c Input encoding file
)
! Missing number, treated as zero.
<to be read again> 
                   {
l.11 \end{pythonBox}
                    
? q
OK, entering \batchmode...

(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/se-utf8.def
File: se-utf8.def 2016/05/16 v1.11 stringenc: UTF-8
)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/se-iso-8859-1.def
File: se-iso-8859-1.def 2016/05/16 v1.11 stringenc: ISO-8859-1
) (aux_dir/test2.listing) [1
[snip]
```

I'm using TeX Live on Linux Mint, installed this month.

I'll see if I can run this on my windows machine some time soon. It might be an OS problem, or a TeX Live problem, so I'll try using TeX Live on windows first.

**Comment by KriPet** [comment] 2016-10-25 14:36
Ok, seems to be  a problem with TeX Live

TeX Live + Windows: Won't work
TeX Live + Linux Mint: Won't work
MikTex + Windows: Works

I'll see if I can find someone else to bother about fixing this. Thanks for the help, in any case.

**Comment by T-F-S** [comment] 2016-11-17 14:10
I will close this issue for now, but you may reopen it or create a new one, if you think that the `tcolorbox` code can be enhanced.

**Closed by T-F-S** 2016-11-17 14:10 UTC
Labels: bug, enhancement
